\documentclass[a4paper]{article}
\usepackage{a4wide}
\usepackage[utf8]{inputenc}














\section{LC stability - the View on independent Retention Time Peptides}

The monitor the stability of the liquid chromatography, we spike in the iRT-kit (commercialized by Biognosys). These are artifical peptides which have strong signal response and are usually spread over the whole retention time gradient. 
We make use of them to see how reproducible the LC is working by monitorring the iRT peptides with respect to rt-elution, signal response (Intensity) and elution time length.

\begin{figure}[htbp]
<<echo=FALSE,fig=TRUE>>=
library(stringr) #useful for catching iRT peptides
f <- "maxquant/evidence.txt"
dat <- read.table(f, header=T, sep="\t")
# how many do we find?
#iRTpep <- str_count(dat$Leading.Razor.Protein, "iRT_protein")
iRTpep <- str_count(dat$Leading.Razor.Protein, "ZZ_FGCZCont0260")

paste("Total MSMS for iRT peptides: ", sum(iRTpep),sep="")
#Bool iRT

bool_iRT <- iRTpep ==1
dat_iRT <- dat[bool_iRT,]
#generate overview
plot(dat_iRT$Calibrated.retention.time)
@
  \caption{We show how many iRTs are found and the overall distribution over the retention time gradient}
  \label{fig:iRToverview}
\end{figure}


\begin{figure}[htbp]
<<echo=FALSE,fig=TRUE>>=
# how are they spread in RT?
bwplot(dat_iRT$Calibrated.retention.time~dat_iRT$Raw.file|dat_iRT$Sequence, scales = list(x = list(rot = 90, cex=0.3)), par.strip.text = list(cex = 0.5), main="Retention time of iRT-peptides", ylab="Retention time")
@
  \caption{Overview of eluting retention time peptides in the different raw-files}
  \label{fig:iRTrt}
\end{figure}

\begin{figure}[htbp]
<<echo=FALSE,fig=TRUE>>=
# how are they spread in RT?
bwplot(dat_iRT$Retention.time~dat_iRT$Raw.file|dat_iRT$Sequence, scales = list(x = list(rot = 90, cex=0.3)), par.strip.text = list(cex = 0.5), main="Uncalibrated retention time of iRT-peptides", ylab="Retention time")
@
  \caption{Overview of eluting retention time peptides (uncalibrated retention time) in the different raw-files}
  \label{fig:iRTrt_uncal}
\end{figure}


\begin{figure}[htbp]
<<echo=FALSE,fig=TRUE>>=
# how are they intensity wise?
bwplot(dat_iRT$Intensity~dat_iRT$Raw.file|dat_iRT$Sequence, scales = list(x = list(rot = 90, cex=0.3)), par.strip.text = list(cex = 0.5), ylab="Intensity", main="Signal Response (Intensity) of iRT-peptides")
@
  \caption{Overview of the intensities for retention time peptides in the different raw-files}
  \label{fig:iRTInt}
\end{figure}


\begin{figure}[htbp]
<<echo=FALSE,fig=TRUE>>=
# elution length
bwplot(dat_iRT$Retention.length~dat_iRT$Raw.file|dat_iRT$Sequence, scales = list(x = list(rot = 90, cex=0.3)), , par.strip.text = list(cex = 0.5), ylab="Retention time window", main="Retention time window of iRT-peptides")
@
  \caption{Overview of elution time windows for  iRT peptides in the different raw-files}
  \label{fig:iRTWindow}
\end{figure}



\section{Disclaimer and Acknowledgements}
This QC script is written by J. Grossmann using in Sweave-R and processes text files which are exported from MaxQuant v.1.4.0.1 and ScaffoldV4.
It is purely descriptive.
\\
\\
Deep thanks go to C. Panse, S. Barkow and W. Wolski who provided stimulating environment and/or a template for this QC report.

\end{document}